name: turistautak
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^1.1.1
  flutter_map_location_marker: ^4.1.1
  flutter_map_tile_caching:
    git:
      url: https://github.com/sn4k3ch4rm3r/flutter_map_tile_caching
      ref: v5
  latlong2: ^0.8.1
  dynamic_color: ^1.4.0
  geolocator: ^9.0.0
  map_elevation:
    git:
      url: https://github.com/sn4k3ch4rm3r/map_elevation
  file_picker: ^4.6.1
  sqflite: ^2.0.3
  shared_preferences: ^2.0.15
  gpx: ^2.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.3
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/